# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:33:02+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    TdcerCertificatePostRequest,
    TdcerCertificatePostResponse,
    TdcerCertificatePostResponse1,
    TdcerCertificatePostResponse2,
    TdcerCertificatePostResponse3,
    TdcerCertificatePostResponse4,
    TdcerCertificatePostResponse5,
    TdcerCertificatePostResponse6,
)

app = MCPProxy(
    description='APIs provided by UCO Bank.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='UCO Bank',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/ucobank/v3'}],
)


@app.post(
    '/tdcer/certificate',
    description=""" API to verify TDS Certificate. """,
    tags=['tds_certificate_operations'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def tdcer(body: TdcerCertificatePostRequest = None):
    """
    TDS Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
